import type { ReactNode } from 'react';

export const metadata = {
  title: 'Degens War',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}